service: serverless-lambda-demo
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: todos # path will be domain.name.com/dev/notes
          method: post
          cors: true
  getOne: 
    handler: handler.getOne
    events: 
      - http: 
          path: todos/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events: 
      - http:
          path: todos
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: todos/{id} # path will be domain.name.com/dev/notes/1
          method: delete
          cors: true

